blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/detail/<int:pk>', views.post_detail, name="post_detail"),
    # path('posts/<int:pk>', views.PostDetailView.as_view(), name="post_detail"),
    path('ticket', views.ticket, name="ticket"),
    path('posts/<int:pk>/comment', views.post_comment, name="post_comment"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<int:pk>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<int:pk>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<int:pk>', views.delete_image, name="delete_image"),
    # path('login', views.user_login, name="login"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout', views.log_out, name="logout"),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password-change_done"),

    # url to reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password_reset/complete/'), name="password_reset_confirm"),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('register', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls', namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
from django.template.defaultfilters import slugify


# Managers
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        # DRAFT = 'DF', 'پیشنویس'
        # PUBLISHED = 'PB', 'انتشار'
        # REJECTED = 'RJ', 'رد شده'
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        REJECTED = 'RJ', 'Rejected'

    CATEGORY_CHOICES =(
        ('تکنولوژی', 'تکنولوژی'),
        ('برنامه نویسی', 'برنامه نویسی'),
        ('هوش مصنوعی', 'هوش مصنوعی'),
        ('سایر', 'سایر'),
    )

    # relations
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_post", verbose_name="نویسنده")
    # data fields
    title = models.CharField(max_length=250, verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    slug = models.SlugField(max_length=250)
    # date fields
    publish = jmodels.jDateTimeField(default=timezone.now, verbose_name="تاریخ انتشار")
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    # choices field
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name="وضعیت")
    reading_time = models.PositiveIntegerField(verbose_name="زمان مطالعه")
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default="سایر", verbose_name="دسته بندی")

    # objects = models.Manager()
    objects = jmodels.jManager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for img in self.images.all():
            storage, path = img.image_file.storage, img.image_file.path
            storage.delete(path)
        return super().delete(*args, **kwargs)


class Ticket(models.Model):
    message = models.TextField(verbose_name="پیام")
    name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    phone = models.CharField(max_length=11, verbose_name="شماره تلفن")
    email = models.EmailField(max_length=250, verbose_name="ایمیل")
    subject = models.CharField(max_length=250, verbose_name="موضوع")

    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="پست")
    name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    body = models.TextField(verbose_name="متن کامنت")
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")
    active = models.BooleanField(default=False, verbose_name="وضعیت")

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return f"{self.name}: {self.post}"


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images", verbose_name="پست")
    image_file = ResizedImageField(upload_to="post_image/", quality=75, crop=['middle', 'center'], size=[500, 500])
    title = models.CharField(max_length=250, verbose_name="عنوان", null=True, blank=True)
    description = models.TextField(verbose_name="توضیحات", null=True, blank=True)
    created = jmodels.jDateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "تصویر"
        verbose_name_plural = "تصویر ها"

    def delete(self, *args, **kwargs):
        storage, path = self.image_file.storage, self.image_file.path
        storage.delete(path)
        return super().delete(*args, **kwargs)

    def __str__(self):
        return self.title if self.title else "None"


class Account(models.Model):
    user = models.OneToOneField(User, related_name="account", on_delete=models.CASCADE, verbose_name="کاربر")
    date_of_birth = jmodels.jDateField(verbose_name="تاریخ تولد", blank=True, null=True)
    bio = models.TextField(verbose_name="بایو", blank=True, null=True)
    job = models.CharField(verbose_name="شغل", max_length=250, blank=True, null=True)
    photo = ResizedImageField(blank=True, null=True, upload_to="account_image/", quality=60, crop=['middle', 'center'], size=[500, 500],
                              verbose_name="تصویر پروفایل")

    class Meta:
        verbose_name = "اکانت"
        verbose_name_plural = "اکانت ها"

    def __str__(self):
        return self.user.username

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.http import HttpResponse, Http404
from .models import *
from .form import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
# from django.db.models import Q
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 6)
    page_num = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_num)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog/list.html", context)
    # return HttpResponse('Post List')
# class PostListView(ListView):
#     # model = Post
#     queryset = Post.published.all()
#     template_name = 'blog/list.html'
#     paginate_by = 3
#     context_object_name = "posts"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    # try:
    #     post = Post.published.get(id=pk)
    # except:
    #     raise Http404("Not Found :((")
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, "blog/detail.html", context)
    # return HttpResponse(f"post: {pk}")


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    # روش اول برای ایجاد آبجکت تیکت 👇🏻
    # if request.method == "POST":
    #     form = TicketForm(request.POST)
    #     if form.is_valid():
    #         ticket_obj = Ticket.objects.create()
    #         cd = form.cleaned_data
    #         ticket_obj.message = cd['message']
    #         ticket_obj.name = cd['name']
    #         ticket_obj.phone = cd['phone']
    #         ticket_obj.email = cd['email']
    #         ticket_obj.subject = cd['subject']
    #         ticket_obj.save()
    #         return redirect('blog:index')
    # else:
    #     form = TicketForm()
    # روش دوم برای ایجاد آبجکت تیکت 👇🏻
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, 'form/ticket.html', {"form": form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "form/comment.html", context)


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)) \
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    return render(request, "blog/profile.html", {'posts': posts})


@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['img1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['img2'], post=post)
            return redirect("blog:profile")
    else:
        form = CreatePostForm()
    return render(request, "form/create_post.html", {'form': form})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'form/delete-post.html', {'post': post})


@login_required
def delete_image(request, pk):
    image = get_object_or_404(Image, id=pk)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['img1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['img2'], post=post)
            return redirect("blog:profile")
    else:
        form = CreatePostForm(instance=post)
    context = {
        'form': form,
        'post': post
    }
    return render(request, "form/create_post.html", context)


# function to login user👇🏻
# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('شما در سایت غیرفعال شده اید.')
#             else:
#                 return HttpResponse('همچین کاربری در سایت وجود ندارد.')
#     else:
#         form = LoginForm()
#     return render(request, 'form/login.html', {'form': form})

# function to logout user
def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, files=request.FILES, instance=request.user.account)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'user_form': user_form,
        'account_form': account_form
    }
    return render(request, 'registration/edit_account.html', context)

blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% load static %}
{% load blog_tags %}
{% load jformat %}

{% block head %}    {% endblock %}


{% block content %}

<!-- Preloader START -->
	<div class="preloader">
		<div class="loader">
			<div class="sh1"></div>
			<div class="sh2"></div>
		</div>
	</div>
<!-- Preloader END -->

<main>

<section class="pt-4">
	<div class="container">
		<div class="row">
      <div class="col-12">
				<div class="border p-4 text-center rounded-3">
                    {% if category %}
                        <h1><a href="{% url 'blog:post_list' %}" > لیست پست های {{ category }}</a></h1>
                    {% else %}
                        <h1><a href="{% url 'blog:post_list' %}" >لیست پست ها</a></h1>
                    {% endif %}
					<nav class="d-flex justify-content-center" aria-label="breadcrumb">
					</nav>
				</div>
      </div>
    </div>
	</div>
</section>

<section class="position-relative pt-0">
	<div class="container" data-sticky-container>
		<div class="row">
			<!-- Main Post START -->
			<div class="col-lg-9">
				<!-- Card item START -->
                {% for post in posts %}
				<div class="card mb-4">
					<div class="row">
						<div class="col-md-5">
							<img class="rounded-3" src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
						</div>
						<div class="col-md-7 mt-3 mt-md-0">
							<a href="#" class="badge text-bg-danger mb-2"><i class="fas fa-circle me-2 small fw-bold"></i>{{ post.category}}</a>
							<h4><a href="{{post.get_absolute_url}}" class="btn-link stretched-link text-reset">{{ post.title}}</a></h4>
							<p>{{ post.description | markdown | truncatewords:40 }} </p>
							<!-- Card info -->
							<ul class="nav nav-divider align-items-center d-none d-sm-inline-block">
								<li class="nav-item">
									<div class="nav-link">
										<div class="d-flex align-items-center position-relative">
											<div class="avatar avatar-xs">
												<img class="avatar-img rounded-circle" src="{{ post.author.account.photo.url }}" alt="avatar">
											</div>
											<span class="ms-3">توسط <a href="#" class="stretched-link text-reset btn-link">{{ post.author }}</a></span>
										</div>
									</div>
								</li>
								<li class="nav-item">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</li>
							</ul>
						</div>
					</div>
				</div>
                {% endfor %}
				<!-- Card item END -->

			</div>
			<!-- Main Post END -->

			<!-- Sidebar START -->
			<div class="col-lg-3 mt-5 mt-lg-0">
				<div data-sticky data-margin-top="80" data-sticky-for="767">
					<!-- Trending topics widget START -->
					<div>
						<h4 class="mb-3">دسته بندی</h4>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url("#"); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog:post_list_category' 'تکنولوژِی' %}" class="stretched-link btn-link text-white h5">تکنولوژِی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/02.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}" class="stretched-link btn-link text-white h5">هوش مصنوعی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/03.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog:post_list_category' 'زبان برنامه نویسی' %}" class="stretched-link btn-link text-white h5">زبان برنامه نویسی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/04.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog:post_list_category' 'بلاکچین' %}" class="stretched-link btn-link text-white h5">بلاکچین</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/05.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog:post_list_category' 'سایر' %}" class="stretched-link btn-link text-white h5">سایر</a>
							</div>
						</div>
						<!-- View All Category button -->
						<div class="text-center mt-3">
							<a href="{% url 'blog:post_list' %}" class="text-muted text-primary-hover"><u>مشاهده همه</u></a>
						</div>
					</div>
					<!-- Trending topics widget END -->

					<div class="row">
						<!-- Recent post widget START -->
						<div class="col-12 col-sm-6 col-lg-12">
							<h4 class="mt-4 mb-3">پربحث ترین ها</h4>
							<!--  post item -->
                            {% most_popular_posts 5 as pop_posts %}
                            {% for post in pop_posts %}
							<div class="card mb-3">
								<div class="row g-3">
									<div class="col-4">
										<img class="rounded" src="{{ post.images.first.image_file.url}}" alt="">
									</div>
									<div class="col-8">
										<h6><a href="{{post.get_absolute_url}}" class="btn-link stretched-link text-reset">{{post.title}}</a></h6>
										<div class="small mt-1">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</div>
									</div>
								</div>
							</div>
                            {% endfor %}
						</div>
						<!--  post widget END -->

					</div>
				</div>
			</div>
			<!-- Sidebar END -->
		</div> <!-- Row end -->
	</div>
</section>
</main>

	<div class="back-top"><i class="bi bi-arrow-up-short"></i></div>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/sticky-js/sticky.min.js' %}"></script>
	<script src="{% static 'js/functions.js' %}"></script>
{#    {% include "partials/pagination.html" with page=page_obj%}#}
    {% include "partials/pagination.html" with page=posts%}
{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% block title %}profile{% endblock %}
{% load static %}
{% load blog_tags %}
{% load jformat %}
{% block head %} {% endblock %}

{% block content %}

<!-- Preloader START -->
	<div class="preloader">
		<div class="loader">
			<div class="sh1"></div>
			<div class="sh2"></div>
		</div>
	</div>
<!-- Preloader END -->

<section class="py-4">
	<div class="container">
    <div class="row pb-4">
			<div class="col-12">
        <!-- Title -->
				<div class="d-sm-flex justify-content-sm-between align-items-center">
					<h1 class="mb-2 mb-sm-0 h3">منوی کاربری</h1>
					<a href="{% url 'blog:create_post' %}" class="btn btn-sm btn-primary mb-0"><i class="fas fa-plus me-2"></i>ایجاد پست جدید</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-12">

          <div class="row g-4 mb-4">
            <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:password_change' %}"><i class="bi bi-pen fa-fw me-2"></i>تغییر پسورد</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>

               <div class="col-sm-4 col-lg-3">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:edit_account' %}"><i class="bi bi-pencil fa-fw me-2"></i>تغییر اطلاعات شخصی</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>


                          <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:logout' %}"><i class="bi bi-power fa-fw me-2"></i>خروج</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>

                             <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:ticket' %}"><i class="bi bi-messenger fa-fw me-2"></i>ارسال تیکت</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>


            </div>
          </div>
          <!-- Post list table START -->
          <div class="card border bg-transparent rounded-3">

              <!-- Post list table START -->
              <div class="table-responsive border-0">
                <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                  <!-- Table head -->
                  <thead class="table-dark">
                    <tr>
                      <th scope="col" class="border-0">ردیف</th>
                      <th scope="col" class="border-0">عنوان</th>
                      <th scope="col" class="border-0">تاریخ انتشار</th>
                      <th scope="col" class="border-0">وضعیت</th>
                      <th scope="col" class="border-0 rounded-end">عملیات</th>
                    </tr>
                  </thead>

                  <!-- Table body START -->
                  <tbody class="border-top-0">
                    <!-- Table item -->
                    {% for post in posts %}
                    <tr>
                      <!-- Table data -->
                      <td>
                        <h6 class="course-title mt-2 mt-md-0 mb-0"><a href="#">{{ forloop.counter}}</a></h6>
                      </td>
                       <!-- Table data -->
                      <td>
                        <a href="{{ post.get_absolute_url }}" class="badge text-bg-success mb-2">{{ post.title }}</a>
                      </td>
                      <!-- Table data -->
                      <td>{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</td>

                      <!-- Table data -->
                      <td>
                        <span class="badge bg-warning bg-opacity-15 text-warning mb-2">{{ post.status}}</span>
                      </td>
                      <!-- Table data -->
                      <td>
                        <div class="d-flex gap-2">
                          <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-light btn-round mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="حذف"><i class="bi bi-trash"></i></a>
                          <a href="{% url 'blog:edit_post' post.id%}" class="btn btn-light btn-round mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="ویرایش"><i class="bi bi-pencil-square"></i></a>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  <!-- Table body END -->
                </table>
              </div>
              <!-- Post list table END -->
            </div>
          </div>
          <!-- Post list table END -->
      </div>
    </div>
  </div>
</section>
<!-- =======================
Main contain END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<!-- Back to top -->
<div class="back-top"><i class="bi bi-arrow-up-short"></i></div>
<!-- =======================
JS libraries, plugins and custom scripts -->

<!-- Bootstrap JS -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Vendors -->
<script src="{% static 'vendor/apexcharts/js/apexcharts.min.js' %}"></script>
<script src="{% static 'vendor/quill/js/quill.min.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'js/functions.js' %}"></script>


{% endblock %}